import { ProfilPreset } from '../types';

export const PROFIL_PRESETS: ProfilPreset[] = [
  {
    id: 'mint',
    name: 'MINT / Naturwissenschaft',
    untertitel: 'Mathematik • Physik • Englisch',
    beschreibung: 'Klassisches naturwissenschaftlich-technisches Profil mit fundierter MINT-Ausrichtung.',
    badge: 'MINT-Profil',
    faecher: [
      { name: 'Mathematik', typ: 'LF' },
      { name: 'Physik', typ: 'LF' },
      { name: 'Englisch', typ: 'LF' },
      { name: 'Deutsch', typ: 'BF', muendlich: true },
      { name: 'Geschichte', typ: 'BF' },
      { name: 'Geographie', typ: 'BF' },
      { name: 'Gemeinschaftskunde', typ: 'BF' },
      { name: 'Religionslehre', typ: 'BF', muendlich: true },
      { name: 'Bildende Kunst', typ: 'BF' },
      { name: 'Chemie', typ: 'BF' },
      { name: 'Biologie', typ: 'BF' },
      { name: 'Sport', typ: 'BF' },
    ],
  },
  {
    id: 'sprachen',
    name: 'Neusprachliches Profil',
    untertitel: 'Englisch • Französisch • Deutsch',
    beschreibung: 'Schwerpunkt auf moderner Sprachkompetenz, Literatur und interkultureller Kommunikation.',
    badge: 'Sprach-Profil',
    faecher: [
      { name: 'Deutsch', typ: 'LF' },
      { name: 'Englisch', typ: 'LF' },
      { name: 'Französisch', typ: 'LF' },
      { name: 'Mathematik', typ: 'BF', muendlich: true },
      { name: 'Geschichte', typ: 'BF', muendlich: true },
      { name: 'Geographie', typ: 'BF' },
      { name: 'Gemeinschaftskunde', typ: 'BF' },
      { name: 'Ethik', typ: 'BF' },
      { name: 'Musik', typ: 'BF' },
      { name: 'Biologie', typ: 'BF' },
      { name: 'Sport', typ: 'BF' },
    ],
  },
  {
    id: 'gesellschaft',
    name: 'Gesellschaftswissenschaften',
    untertitel: 'Geschichte • Mathematik • Englisch',
    beschreibung: 'Fokus auf historische Prozesse, Politik, Gesellschaft und analytisches Denken.',
    badge: 'Gesellschafts-Profil',
    faecher: [
      { name: 'Geschichte', typ: 'LF' },
      { name: 'Mathematik', typ: 'LF' },
      { name: 'Englisch', typ: 'LF' },
      { name: 'Deutsch', typ: 'BF', muendlich: true },
      { name: 'Geographie', typ: 'BF' },
      { name: 'Gemeinschaftskunde', typ: 'BF' },
      { name: 'Religionslehre', typ: 'BF', muendlich: true },
      { name: 'Bildende Kunst', typ: 'BF' },
      { name: 'Physik', typ: 'BF' },
      { name: 'Biologie', typ: 'BF' },
      { name: 'Sport', typ: 'BF' },
    ],
  },
  {
    id: 'kunst',
    name: 'Musisch-Künstlerisch',
    untertitel: 'Bildende Kunst • Deutsch • Biologie',
    beschreibung: 'Gestalterisches Profil mit bildender Kunst, kreativer Entfaltung und biologischen Grundlagen.',
    badge: 'Kreativ-Profil',
    faecher: [
      { name: 'Bildende Kunst', typ: 'LF' },
      { name: 'Deutsch', typ: 'LF' },
      { name: 'Biologie', typ: 'LF' },
      { name: 'Mathematik', typ: 'BF', muendlich: true },
      { name: 'Geschichte', typ: 'BF', muendlich: true },
      { name: 'Englisch', typ: 'BF' },
      { name: 'Geographie', typ: 'BF' },
      { name: 'Gemeinschaftskunde', typ: 'BF' },
      { name: 'Religionslehre', typ: 'BF' },
      { name: 'Chemie', typ: 'BF' },
      { name: 'Sport', typ: 'BF' },
    ],
  },
  {
    id: 'informatik',
    name: 'Informatik & MINT',
    untertitel: 'Mathematik • Biologie • Deutsch',
    beschreibung: 'Moderne Kombination aus MINT-Schwerpunkt und Wahlfach Informatik in der mündlichen Prüfung.',
    badge: 'Informatik-Profil',
    faecher: [
      { name: 'Mathematik', typ: 'LF' },
      { name: 'Biologie', typ: 'LF' },
      { name: 'Deutsch', typ: 'LF' },
      { name: 'Englisch', typ: 'BF' },
      { name: 'Geschichte', typ: 'BF', muendlich: true },
      { name: 'Geographie', typ: 'BF' },
      { name: 'Gemeinschaftskunde', typ: 'BF' },
      { name: 'Ethik', typ: 'BF' },
      { name: 'Musik', typ: 'BF' },
      { name: 'Chemie', typ: 'BF' },
      { name: 'Wahlfach Informatik', typ: 'WF', muendlich: true },
      { name: 'Sport', typ: 'BF' },
    ],
  },
];
